---
name: renovate-config-validator
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    paths:
      - .github/renovate.json5
      - "**.json5"
  workflow_dispatch:
permissions:
  contents: read
jobs:
  validate_renovate_config:
    name: Validate Renovate Config
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        config:
          - .github/renovate.json5
          - default.json5
          - managers.json5
          - package-rules-groupings.json5
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        # yamllint disable-line rule:line-length
      - uses: suzuki-shunsuke/github-action-renovate-config-validator@c22827f47f4f4a5364bdba19e1fe36907ef1318e # v1.1.1
        with:
          config_file_path: ${{ matrix.config }}
