---
name: Semantic Pull Request
on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
permissions:
  pull-requests: read
jobs:
  validate_pr_title:
    name: Validate PR Title
    runs-on: ubuntu-latest
    steps:
      # https://github.com/amannn/action-semantic-pull-request
      - uses: amannn/action-semantic-pull-request@0723387faaf9b38adef4775cd42cfd5155ed6017 # v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
